services:
  - type: web
    name: stego-vault
    runtime: python
    pythonVersion: "3.11.0"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
